# -*- coding: utf-8 -*-
"""Module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q8tea_D8Rj-mjwYtpd7Cit_fI8_uwwWK

https://docs.python.org/pt-br/3/tutorial/modules.html

#Declaração de Variáveis
"""

#ID do databank
data = '962'

#dict para armazenar dados da função ID
ID_dict = {}

#gases com permeabilidades presentes no banco de dados ordem crescente de kinetic diameter
gases = ('He','H2','CO2','O2','H2S','N2','CO','CH4','C2H6','SF6') #EM ORDEM
gases_kinetic_diameter = {'He':260,
                          'H2':289,
                          'CO2':330,
                          'Ar':340,
                          'O2':346,
                          'H2S':360,
                          'N2':364,
                          'CO':376,
                          'CH4':380,
                          'C2H6':444.3,
                          'SF6':550,
                          'none':0}
gases_effec_diameter = {'He':178, #T>Tg
                        'H2':214,
                        'CO2':302,
                        'O2':289,
                        'Ar':297,
                        'H2S':None,
                        'N2':304,
                        'CO':304,
                        'CH4':318,
                        'C2H6':346,
                        'SF6':None,
                        'none':0}
                        
                        
#frequencia de dados para cada gas em situação "pura" e "mixtura"
count_pure = {}
count_mixture = {}


#nome das colunas correspondentes à características da membrana e do processo seus respectivos índices na coluna
#EM ORDEM:
columns_membrane = ['type', 'description', 'support_material', 'subtype', 'filler_loading',
                    'previous_thickness', 'mean_thickness', 'mean_pore_size', 'pore_volume',
                    'specific_surface_area',  'aging']
columns_process = ['surface_area', 'temperature', 'feed_pressure', 'permeate_pressure',
                   'delta_pressure', 'feed_flow_rate', 'sweep_gas', 'sweep_gas_flow',
                   'stage_cut']
columns_others = ['provided_data_type', 'in_reference_data_location', 'reference', 'url']

columns_membrane_index = {}
columns_process_index = {}
columns_others_index = {}

#A performance de cada gás foi representada pela seguintes variáveis:
prefix1='x_' #Fração mássica/molar/volumétrica
prefix2='Py_' #Permeabilidade
prefix3='Pe_' #Permeância

meu_amor = 'Rafael'